### ISSUE TITLE
New block is not applied on the node that mined the block

### ISSUE THREAD

**Issue by mihaigiurgeanu** [adjoint-io/nanocoin#32]
When a node mines a block, and the node is not in the boot nodes, the block is not applied on this node. It is applied on all the other nodes.

This makes the current node to not be able to participate in the blockchain because blocks mined by others will have an invalid index for this node.

**Comment by tdietert** [comment]
I think this is a bigger issue with peer discovery not full working as it should-- the bootnodes should be the nodes that are "always on" and carry the most recent peer list in the network; I.E. A server I'm running that tracks all the peers in the network. Not all peers should _need_ to be in the bootnodes list for peer discovery and block application to work. This can be fixed by on response to a query for peers from a non-bootnode, the bootnode responds with a list of the peers it knows about, and also adds the peer who queried for peers to it's peer list. It involves a fix to the `onPeerQuery` function found here: https://github.com/tdietert/nanocoin/blob/master/src/Nanocoin/Network/P2P.hs#L123, though I'm not too sure why it's not working at the moment. Unfortunately, I don't think your PR #33 properly addresses the bug-- I'll have a look at it sometime later this week or this weekend, but you're also welcome to try to fix this issue in the peer discovery module `Nanocoin.Network.P2P` yourself if you find the time :+1:
